version: '3.5'

services:

  # schelly:
    # image: flaviostutz/schelly
    # ports:
      # - 8080:8080
    # environment:
      # - LOG_LEVEL=debug
      # - BACKUP_NAME=schelly-pgdump
      # - WEBHOOK_URL=http://localhost:7070/backups
      # - BACKUP_CRON_STRING=0 */1 * * * *
      # - RETENTION_MINUTELY=5
      # - WEBHOOK_GRACE_TIME=20

  mysql-api:
    build: .
    ports:
      - 7070:7070
    environment:
      - LOG_LEVEL=debug
      - S3_PATH=/mysql
      - S3_BUCKET=bem-backups-dev
      - S3_REGION=us-west-1
      - DUMP_CONNECTION_NAME=bem_saude
      - DUMP_CONNECTION_HOST=docker.for.win.localhost:3306
      - DUMP_CONNECTION_AUTH_USERNAME=bem_saude
      - DUMP_CONNECTION_AUTH_PASSWORD=bem_saude
      - AWS_ACCESS_KEY_ID=aaaaaaaaaa
      - AWS_SECRET_ACCESS_KEY=aaaaaaaaaa
    